version: 0.0
os: linux

files:
  - source: LoginWebApp-1.0.0.war
    destination: /opt/apache-tomcat-9.0.93/webapps/login

hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root
