version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - ls -R target

artifacts:
  base-directory: target
  files:
    - 'LoginWebApp-1.war'
  discard-paths: yes
