version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install

artifacts:
  files:
    - '**/LoginWebApp-1.war'
    - 'appspec.yaml'
  discard-paths: yes
  base-directory: target  
  name: LoginWebApp-1.war 
  discard-paths: yes
  s3-bucket: java-artifacts-devops4solutions1
